---
# Εκτελούμε πρώτα το playbook εγκατάστασης και αρχικής ρύθμισης του MicroK8s cluster
- import_playbook: microk8s_install.yml

# Στη συνέχεια εφαρμόζουμε όλα τα βασικά Kubernetes manifests της εφαρμογής (db, minio, mailhog, backend, frontend, ingress)
- import_playbook: k8s_apply_core.yml

