services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      # Persistent volume για τα δεδομένα της PostgreSQL
      - pgdata:/var/lib/postgresql/data

      # SQL seed + φωτογραφίες από shared /vagrant
      - /vagrant/data/sqlData:/seed:ro
      - /vagrant/data/sqlData/photos/avatar_photos:/photos/avatar_photos:ro
      - "/vagrant/data/sqlData/photos/property_photos :/photos/property_photos:ro"

      # παλιά mounts
      - /opt/DS-2025:/ds2025:ro
      - /opt/DS-2025/photos:/photos_src:ro

    # Expose PostgreSQL προς το host
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo_user -d demo_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  mailhog:
    image: mailhog/mailhog
    ports:
      # SMTP
      - "1025:1025"
      # Web
      - "8025:8025"

  minio:
    image: minio/minio
    # Εκκίνηση server + console
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      # Persistent storage για MinIO
      - minio_data:/data
    ports:
      # API
      - "9000:9000"
      # Console
      - "9001:9001"

  backend:
    # Online image από GitHub Container Registry
    image: ghcr.io/it2022031/ds2025-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo_db
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo_pass
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: ds2025
      MINIO_ENDPOINT: http://minio:9000
      APP_PUBLIC_BASE_URL: "http://127.0.0.1:8081"
      APP_FRONTEND_URL: "http://127.0.0.1:8081"

    # Περιμένει να είναι healthy η βάση
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    # Online image από GHCR
    image: ghcr.io/it2022031/ds2025-frontend:latest
    depends_on:
      - backend
    # Frontend στο host
    ports:
      - "8081:80"

volumes:
  pgdata:
  minio_data:
